name: Deploy Documentation
on: 
  push:
    branches:
      - "!dependabot/**"
      - "*"
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Hexo
        runs: |
          npm install
      
      - name: Build
        runs: |
          npx hexo generate

      # public folder